local:
  hosts:
    127.0.0.1:

prod:
  hosts:
    srv.local:
      ansible_user: '{{ lookup("env", "ANSIBLE_USER") }}'
      ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'

dev:
  hosts:
    dev.local:
      ansible_user: '{{ lookup("env", "ANSIBLE_USER") }}'
      ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'