- name: Local test
  hosts: all
  tasks:
    - name: Simple task
      ansible.builtin.cron:
        name: "test task"
        minute: "*/2"
        job: "ansible-playbook -i prod, /opt/cron/playbooks/ping.yml"
