- name: Cron setup
  hosts: all
  tasks:

    - name: Docker prune
      ansible.builtin.cron:
        name: "docker prune"
        minute: "0"
        hour: "1"
        day: "*"
        month: "*"
        weekday: "6"
        job: "ansible-playbook --limit prod /opt/cron/playbooks/dockerprune.yml"

    - name: Apt update and upgrade
      ansible.builtin.cron:
        name: "apt update upgrade"
        minute: "0"
        hour: "2"
        day: "*"
        month: "*"
        weekday: "6"
        job: "ansible-playbook --limit prod /opt/cron/playbooks/aptupgrade.yml"

    - name: Get disk space state
      ansible.builtin.cron:
        name: "disk space state"
        minute: "0"
        hour: "3"
        day: "*"
        month: "*"
        weekday: "6"
        job: "ansible-playbook --limit prod /opt/cron/playbooks/diskspace.yml"
