- name: Update and upgrade apt packages
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      register: apt
      changed_when: false

    - name: Show apt result
      ansible.builtin.debug:
        msg: "{{ apt.stdout_lines }}"
